// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDubVUrhy_WlWp8mFvFUUq1qPBZW8wCkw8',
    appId: '1:1076276912794:web:8d248b5caa686640163523',
    messagingSenderId: '1076276912794',
    projectId: 'our-app-4d7d0',
    authDomain: 'our-app-4d7d0.firebaseapp.com',
    storageBucket: 'our-app-4d7d0.firebasestorage.app',
    measurementId: 'G-Z066BEWQ0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGPg6IoPXKVmvjz6D2933Lp8Mc0wh0gMc',
    appId: '1:1076276912794:android:49b79eb187fefa7b163523',
    messagingSenderId: '1076276912794',
    projectId: 'our-app-4d7d0',
    storageBucket: 'our-app-4d7d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvfhYWizf5FDML8YbD_ImzgGc89rVLDMk',
    appId: '1:1076276912794:ios:d591fa3cae36ad17163523',
    messagingSenderId: '1076276912794',
    projectId: 'our-app-4d7d0',
    storageBucket: 'our-app-4d7d0.firebasestorage.app',
    iosBundleId: 'com.example.ourApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvfhYWizf5FDML8YbD_ImzgGc89rVLDMk',
    appId: '1:1076276912794:ios:d591fa3cae36ad17163523',
    messagingSenderId: '1076276912794',
    projectId: 'our-app-4d7d0',
    storageBucket: 'our-app-4d7d0.firebasestorage.app',
    iosBundleId: 'com.example.ourApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDubVUrhy_WlWp8mFvFUUq1qPBZW8wCkw8',
    appId: '1:1076276912794:web:074113a7f0bf019d163523',
    messagingSenderId: '1076276912794',
    projectId: 'our-app-4d7d0',
    authDomain: 'our-app-4d7d0.firebaseapp.com',
    storageBucket: 'our-app-4d7d0.firebasestorage.app',
    measurementId: 'G-2MMLGXPLLQ',
  );
}
